[package]
name = "corpus_matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
lineariterator = { version = "0.1.0", git = "https://github.com/witold-k/lineariterator" }
token_db = { version = "0.1.0", git = "https://github.com/witold-k/token_db" }
simplefield = { version = "0.1.0", git = "https://github.com/witold-k/simplefield" }
